import type { OpenAPIV3 } from 'openapi-types'
import {
  afterParam,
  data,
  err,
  forbidden,
  idParam,
  json,
  jsonBody,
  limitParam,
  noContent,
  notFound,
  ok,
  page,
  query,
  rateLimited,
  ref,
  secured,
  serverError,
  str,
  unauthorized,
  validationFailed,
} from './helpers.js'

export const paths: OpenAPIV3.PathsObject = {
  '/api/v1/auth/register': {
    post: {
      tags: ['Auth'],
      summary: 'Register a new organization and owner',
      operationId: 'register',
      requestBody: jsonBody('RegisterRequest'),
      responses: {
        201: ok(
          'Organization, owner and session created (session cookie set)',
          data(ref('AuthSession')),
        ),
        409: err('Conflict: email already registered'),
        422: validationFailed,
        429: rateLimited,
      },
    },
  },
  '/api/v1/auth/login': {
    post: {
      tags: ['Auth'],
      summary: 'Login',
      operationId: 'login',
      requestBody: jsonBody('LoginRequest'),
      responses: {
        200: ok('Authenticated (session cookie set)', data(ref('AuthSession'))),
        401: err('Invalid email or password'),
        422: validationFailed,
        429: rateLimited,
      },
    },
  },
  '/api/v1/auth/password/change': {
    post: {
      tags: ['Auth'],
      summary: 'Change password (revokes other sessions)',
      operationId: 'changePassword',
      security: secured,
      requestBody: jsonBody('PasswordChangeRequest'),
      responses: {
        200: ok('Password updated', data(ref('Message'))),
        401: err('Current password incorrect'),
        422: validationFailed,
      },
    },
  },
  '/api/v1/auth/logout': {
    post: {
      tags: ['Auth'],
      summary: 'Logout (revoke session)',
      operationId: 'logout',
      security: secured,
      responses: { 204: noContent, 401: unauthorized },
    },
  },
  '/api/v1/auth/me': {
    get: {
      tags: ['Auth'],
      summary: 'Get current user, organization and role',
      operationId: 'getMe',
      security: secured,
      responses: {
        200: ok('Current identity', data(ref('Me'))),
        401: unauthorized,
      },
    },
  },
  '/api/v1/companies': {
    get: {
      tags: ['Companies'],
      summary: 'List companies',
      operationId: 'listCompanies',
      security: secured,
      parameters: [
        limitParam,
        afterParam,
        query('name', 'Case-insensitive name filter'),
      ],
      responses: {
        200: ok('Cursor-paginated companies', page('Company')),
        422: validationFailed,
        429: rateLimited,
        500: serverError,
      },
    },
    post: {
      tags: ['Companies'],
      summary: 'Create company',
      operationId: 'createCompany',
      security: secured,
      requestBody: jsonBody('CreateCompanyRequest'),
      responses: {
        201: ok('Company created', data(ref('Company'))),
        401: unauthorized,
        403: forbidden,
        422: validationFailed,
        429: rateLimited,
        500: serverError,
      },
    },
  },
  '/api/v1/companies/{id}': {
    get: {
      tags: ['Companies'],
      summary: 'Get company',
      operationId: 'getCompany',
      security: secured,
      parameters: [idParam],
      responses: {
        200: ok('Company', data(ref('Company'))),
        401: unauthorized,
        404: notFound('Company'),
        429: rateLimited,
        500: serverError,
      },
    },
    patch: {
      tags: ['Companies'],
      summary: 'Update company',
      operationId: 'updateCompany',
      security: secured,
      parameters: [idParam],
      requestBody: jsonBody('UpdateCompanyRequest'),
      responses: {
        200: ok('Company updated', data(ref('Company'))),
        401: unauthorized,
        403: forbidden,
        404: notFound('Company'),
        422: validationFailed,
        429: rateLimited,
        500: serverError,
      },
    },
    delete: {
      tags: ['Companies'],
      summary: 'Soft delete company',
      operationId: 'deleteCompany',
      security: secured,
      parameters: [idParam],
      responses: {
        204: noContent,
        401: unauthorized,
        403: forbidden,
        404: notFound('Company'),
        429: rateLimited,
        500: serverError,
      },
    },
  },
  '/api/v1/contacts': {
    get: {
      tags: ['Contacts'],
      summary: 'List contacts',
      operationId: 'listContacts',
      security: secured,
      parameters: [limitParam, afterParam],
      responses: {
        200: ok('Cursor-paginated contacts', page('Contact')),
        422: validationFailed,
        429: rateLimited,
        500: serverError,
      },
    },
    post: {
      tags: ['Contacts'],
      summary: 'Create contact',
      operationId: 'createContact',
      security: secured,
      requestBody: jsonBody('CreateContactRequest'),
      responses: {
        201: ok('Contact created', data(ref('Contact'))),
        401: unauthorized,
        403: forbidden,
        422: validationFailed,
        429: rateLimited,
        500: serverError,
      },
    },
  },
  '/api/v1/contacts/{id}': {
    get: {
      tags: ['Contacts'],
      summary: 'Get contact',
      operationId: 'getContact',
      security: secured,
      parameters: [idParam],
      responses: {
        200: ok('Contact', data(ref('Contact'))),
        401: unauthorized,
        404: notFound('Contact'),
        429: rateLimited,
        500: serverError,
      },
    },
    patch: {
      tags: ['Contacts'],
      summary: 'Update contact',
      operationId: 'updateContact',
      security: secured,
      parameters: [idParam],
      requestBody: jsonBody('UpdateContactRequest'),
      responses: {
        200: ok('Contact updated', data(ref('Contact'))),
        401: unauthorized,
        403: forbidden,
        404: notFound('Contact'),
        422: validationFailed,
        429: rateLimited,
        500: serverError,
      },
    },
    delete: {
      tags: ['Contacts'],
      summary: 'Soft delete contact',
      operationId: 'deleteContact',
      security: secured,
      parameters: [idParam],
      responses: {
        204: noContent,
        401: unauthorized,
        403: forbidden,
        404: notFound('Contact'),
        429: rateLimited,
        500: serverError,
      },
    },
  },
  '/api/v1/leads': {
    get: {
      tags: ['Leads'],
      summary: 'List leads',
      operationId: 'listLeads',
      security: secured,
      parameters: [
        limitParam,
        afterParam,
        query('status', 'Filter by status', {
          type: 'string',
          enum: ['NEW', 'CONTACTED', 'QUALIFIED', 'CONVERTED', 'DISQUALIFIED'],
        }),
      ],
      responses: {
        200: ok('Cursor-paginated leads', page('Lead')),
        422: validationFailed,
        429: rateLimited,
        500: serverError,
      },
    },
    post: {
      tags: ['Leads'],
      summary: 'Create lead',
      operationId: 'createLead',
      security: secured,
      requestBody: jsonBody('CreateLeadRequest'),
      responses: {
        201: ok('Lead created', data(ref('Lead'))),
        401: unauthorized,
        403: forbidden,
        422: validationFailed,
        429: rateLimited,
        500: serverError,
      },
    },
  },
  '/api/v1/leads/{id}': {
    get: {
      tags: ['Leads'],
      summary: 'Get lead',
      operationId: 'getLead',
      security: secured,
      parameters: [idParam],
      responses: {
        200: ok('Lead', data(ref('Lead'))),
        401: unauthorized,
        404: notFound('Lead'),
        429: rateLimited,
        500: serverError,
      },
    },
    patch: {
      tags: ['Leads'],
      summary: 'Update lead',
      operationId: 'updateLead',
      security: secured,
      parameters: [idParam],
      requestBody: jsonBody('UpdateLeadRequest'),
      responses: {
        200: ok('Lead updated', data(ref('Lead'))),
        401: unauthorized,
        403: forbidden,
        404: notFound('Lead'),
        422: validationFailed,
        429: rateLimited,
        500: serverError,
      },
    },
    delete: {
      tags: ['Leads'],
      summary: 'Soft delete lead',
      operationId: 'deleteLead',
      security: secured,
      parameters: [idParam],
      responses: {
        204: noContent,
        401: unauthorized,
        403: forbidden,
        404: notFound('Lead'),
        429: rateLimited,
        500: serverError,
      },
    },
  },
  '/api/v1/leads/{id}/qualify': {
    post: {
      tags: ['Leads'],
      summary: 'Advance a lead to QUALIFIED',
      description:
        'Walks the lead through CONTACTED -> QUALIFIED in one call. No-op when already QUALIFIED.',
      operationId: 'qualifyLead',
      security: secured,
      parameters: [idParam],
      responses: {
        200: ok('Lead advanced', data(ref('Lead'))),
        401: unauthorized,
        403: forbidden,
        404: notFound('Lead'),
        422: err('Lead status cannot be qualified'),
        429: rateLimited,
        500: serverError,
      },
    },
  },
  '/api/v1/leads/{id}/convert': {
    post: {
      tags: ['Leads'],
      summary: 'Convert a qualified lead into company, contact and deal',
      operationId: 'convertLead',
      security: secured,
      parameters: [idParam],
      requestBody: {
        ...jsonBody('ConvertLeadRequest'),
        required: false,
      },
      responses: {
        201: ok('Lead converted', data(ref('ConversionResult'))),
        401: unauthorized,
        403: forbidden,
        404: notFound('Lead'),
        409: err('Lead is already converted or disqualified'),
        422: err('Lead must be QUALIFIED to convert'),
        429: rateLimited,
        500: serverError,
      },
    },
  },
  '/api/v1/deals': {
    get: {
      tags: ['Deals'],
      summary: 'List deals',
      operationId: 'listDeals',
      security: secured,
      parameters: [
        limitParam,
        afterParam,
        query('stage', 'Filter by pipeline stage', {
          type: 'string',
          enum: ['NEW', 'QUALIFIED', 'PROPOSAL', 'NEGOTIATION', 'WON', 'LOST'],
        }),
      ],
      responses: {
        200: ok('Cursor-paginated deals', page('Deal')),
        422: validationFailed,
        429: rateLimited,
        500: serverError,
      },
    },
    post: {
      tags: ['Deals'],
      summary: 'Create deal',
      operationId: 'createDeal',
      security: secured,
      requestBody: jsonBody('CreateDealRequest'),
      responses: {
        201: ok('Deal created', data(ref('Deal'))),
        401: unauthorized,
        403: forbidden,
        422: validationFailed,
        429: rateLimited,
        500: serverError,
      },
    },
  },
  '/api/v1/deals/{id}': {
    get: {
      tags: ['Deals'],
      summary: 'Get deal',
      operationId: 'getDeal',
      security: secured,
      parameters: [idParam],
      responses: {
        200: ok('Deal', data(ref('Deal'))),
        401: unauthorized,
        404: notFound('Deal'),
        429: rateLimited,
        500: serverError,
      },
    },
    patch: {
      tags: ['Deals'],
      summary: 'Update deal',
      operationId: 'updateDeal',
      security: secured,
      parameters: [idParam],
      requestBody: jsonBody('UpdateDealRequest'),
      responses: {
        200: ok('Deal updated', data(ref('Deal'))),
        401: unauthorized,
        403: forbidden,
        404: notFound('Deal'),
        422: validationFailed,
        409: err('Deal was modified concurrently; retry'),
        429: rateLimited,
        500: serverError,
      },
    },
    delete: {
      tags: ['Deals'],
      summary: 'Soft delete deal',
      operationId: 'deleteDeal',
      security: secured,
      parameters: [idParam],
      responses: {
        204: noContent,
        401: unauthorized,
        403: forbidden,
        404: notFound('Deal'),
        429: rateLimited,
        500: serverError,
      },
    },
  },
  '/api/v1/deals/{id}/advance': {
    post: {
      tags: ['Deals'],
      summary: 'Advance a deal to the next stage',
      operationId: 'advanceDeal',
      security: secured,
      parameters: [idParam],
      requestBody: jsonBody('AdvanceDealRequest'),
      responses: {
        200: ok('Deal advanced', data(ref('Deal'))),
        401: unauthorized,
        403: forbidden,
        404: notFound('Deal'),
        409: err('Deal is already in that stage'),
        422: err('Invalid stage transition'),
        429: rateLimited,
        500: serverError,
      },
    },
  },
  '/api/v1/deals/{id}/win': {
    post: {
      tags: ['Deals'],
      summary: 'Mark a deal as won (only from NEGOTIATION)',
      operationId: 'winDeal',
      security: secured,
      parameters: [idParam],
      responses: {
        200: ok('Deal won', data(ref('Deal'))),
        401: unauthorized,
        403: forbidden,
        404: notFound('Deal'),
        409: err('Deal was modified concurrently; retry'),
        422: err('Deal cannot be won from its current stage'),
        429: rateLimited,
        500: serverError,
      },
    },
  },
  '/api/v1/deals/{id}/lose': {
    post: {
      tags: ['Deals'],
      summary: 'Mark a deal as lost (only from NEGOTIATION)',
      operationId: 'loseDeal',
      security: secured,
      parameters: [idParam],
      responses: {
        200: ok('Deal lost', data(ref('Deal'))),
        401: unauthorized,
        403: forbidden,
        404: notFound('Deal'),
        409: err('Deal was modified concurrently; retry'),
        422: err('Deal cannot be lost from its current stage'),
        429: rateLimited,
        500: serverError,
      },
    },
  },
  '/api/v1/imports': {
    post: {
      tags: ['Imports'],
      summary: 'Start an import',
      operationId: 'createImport',
      security: secured,
      requestBody: jsonBody('CreateImportRequest'),
      responses: {
        202: ok('Import accepted', data(ref('ImportAccepted'))),
        401: unauthorized,
        403: forbidden,
        422: validationFailed,
        429: rateLimited,
        500: serverError,
      },
    },
  },
  '/api/v1/imports/{id}': {
    get: {
      tags: ['Imports'],
      summary: 'Get import status',
      operationId: 'getImport',
      security: secured,
      parameters: [idParam],
      responses: {
        200: ok('Import status', data(ref('ImportJob'))),
        401: unauthorized,
        404: notFound('Import'),
        429: rateLimited,
        500: serverError,
      },
    },
  },
  '/api/v1/exports': {
    post: {
      tags: ['Exports'],
      summary: 'Start an export',
      operationId: 'createExport',
      security: secured,
      requestBody: jsonBody('CreateExportRequest'),
      responses: {
        202: ok('Export accepted', data(ref('ExportJob'))),
        401: unauthorized,
        403: forbidden,
        422: validationFailed,
        429: rateLimited,
        500: serverError,
      },
    },
  },
  '/api/v1/exports/{id}': {
    get: {
      tags: ['Exports'],
      summary: 'Get export status',
      operationId: 'getExport',
      security: secured,
      parameters: [idParam],
      responses: {
        200: ok('Export status', data(ref('ExportJob'))),
        401: unauthorized,
        404: notFound('Export'),
        429: rateLimited,
        500: serverError,
      },
    },
  },
  '/api/v1/exports/{id}/download': {
    get: {
      tags: ['Exports'],
      summary: 'Download a completed export as CSV',
      operationId: 'downloadExport',
      security: secured,
      parameters: [idParam],
      responses: {
        200: {
          description: 'CSV file',
          content: { 'text/csv': { schema: str } },
        },
        401: unauthorized,
        404: notFound('Export file'),
        409: err('Export is not ready for download'),
        429: rateLimited,
        500: serverError,
      },
    },
  },
  '/': {
    get: {
      tags: ['System'],
      summary: 'Service info',
      operationId: 'getServiceInfo',
      responses: {
        200: ok('Service info', ref('ServiceInfo')),
        429: rateLimited,
        500: serverError,
      },
    },
  },
  '/health': {
    get: {
      tags: ['System'],
      summary: 'Liveness probe',
      operationId: 'getHealth',
      responses: {
        200: ok('Service is alive', ref('Health')),
        500: serverError,
      },
    },
  },
  '/ready': {
    get: {
      tags: ['System'],
      summary: 'Readiness probe (database and redis)',
      operationId: 'getReadiness',
      responses: {
        200: ok('All dependencies healthy', ref('Readiness')),
        503: json('A dependency is unavailable', ref('Readiness')),
      },
    },
  },
  '/metrics': {
    get: {
      tags: ['System'],
      summary: 'Process metrics',
      operationId: 'getMetrics',
      responses: {
        200: ok('Process metrics', ref('Metrics')),
        500: serverError,
      },
    },
  },
}
